name: Debezium crypto image build
on:
  push:
    branches:
      - "main"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to quay.io Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build native executable and upload it as an artifact
        uses: maxday/quarkus-native-build-docker-action@1
        with:
          outputName: debezium-crypto-app-runner
          dockerfilePath: Dockerfile.native

      - name: Dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: quay.io/tealc/debezium-crypto-app
          executablePath: debezium-crypto-app-runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/tealc/debezium-crypto-apps:latest
